((nil . (
         (ssh-deploy-root-local . "/Users/chenlong/workspace/lab/datalight/")
         (ssh-deploy-root-remote . "/ssh:root@43.132.247.55:/data/liubangchen/datalight/")
         (ssh-deploy-debug . 1)
         (ssh-deploy-on-explicit-save . 1)
         (ssh-deploy-automatically-detect-remote-changes . 0)
         (ssh-deploy-force-on-explicit-save . 1)
         (ssh-deploy-async . 0)
         (ssh-deploy-verbose . 1)
         )))
